spring:
  datasource:
    url: jdbc:oracle:thin:@10.4.209.214:1521:CSCFOU7
    username: SVCSGORACSCFOSELECTU
    password: SVCSGORACSCFOSELECTU
  mvc:
    throw-exception-if-no-handler-found: true

server:
  servlet:
    session:
      cookie:
        http-only: true
  error:
    whitelabel:
      enabled: false

apiGateway:
  jndiName:

logging:
  level:
    root: INFO
    java.sql: DEBUG
    com.bnp: DEBUG
